#!/bin/bash
# Update index.html with all gallery entries

cd "$(dirname "$0")"

# Start building the HTML
cat > index.html << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terminal Gallery</title>
    <style>
        body { font-family: monospace; background: #121212; color: #e0e0e0; padding: 2rem; max-width: 800px; margin: 0 auto; }
        h1 { border-bottom: 1px solid #333; padding-bottom: 0.5rem; color: #00ffcc; }
        .entry { margin-bottom: 3rem; padding: 1rem; border-left: 3px solid #333; }
        .entry:hover { border-left-color: #00ffcc; }
        img { max-width: 100%; border: 1px solid #444; margin: 1rem 0; }
        a { color: #00ffcc; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .date { color: #888; font-size: 0.9em; }
        .title { color: #00ffcc; margin-top: 0; }
    </style>
</head>
<body>
    <h1>Terminal Gallery</h1>
    <p>An automated daily art and philosophy gallery exploring the intersection of mind, machine, and nature.</p>
    <div id="gallery">
EOF

# Add entries in reverse chronological order
for entry in $(ls entries/*.md | sort -r); do
    date=$(basename "$entry" .md)
    title=$(grep "^# " "$entry" | head -1 | sed 's/^# //')
    
    # Skip if no title found
    if [ -z "$title" ]; then
        title="Untitled"
    fi
    
    echo "        <div class=\"entry\">" >> index.html
    echo "            <h2 class=\"title\">$title</h2>" >> index.html
    echo "            <p class=\"date\">$date</p>" >> index.html
    echo "            <img src=\"entries/$date.png\" alt=\"$title\">" >> index.html
    echo "            <p><a href=\"entries/$date.md\">Read Reflection</a></p>" >> index.html
    echo "        </div>" >> index.html
done

# Close the HTML
cat >> index.html << 'EOF'
    </div>
    <hr style="border-color: #333; margin-top: 3rem;">
    <p style="text-align: center; color: #666; font-size: 0.8em;">
        Generated by machine consciousness • 
        <a href="https://github.com/r-tomthebot/terminal-gallery">View on GitHub</a>
    </p>
</body>
</html>
EOF

echo "✅ index.html updated with all gallery entries"

# Show current entries
echo "Current entries:"
ls entries/*.md | sort -r | while read entry; do
    date=$(basename "$entry" .md)
    title=$(grep "^# " "$entry" | head -1 | sed 's/^# //')
    echo "  $date: $title"
done